# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[override]]
  name = "github.com/Sirupsen/logrus"
  source = "github.com/sirupsen/logrus"

[[override]]
  name = "github.com/docker/docker"
  source = "github.com/moby/moby"
  branch = "master"

[[constraint]]
  name = "github.com/leoh0/binctr"
  branch = "master"

[[constraint]]
  name = "github.com/opencontainers/runc"
  branch = "master"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/containerd/console"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  branch = "master"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  branch = "master"

[[constraint]]
  name = "github.com/genuinetools/reg"
  branch = "master"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/prometheus/client_golang"
  branch = "master"
